feat: Set up catalog app (sandbox)
status-im/StatusQ pull request #24
Opened 2021-05-04 18:36 UTC by borismelnik

#5 

From Qt Creator:
1. Open in Qt Creator file `sandbox.pro`
2.  Build :)
3.  Run

From console:
1. run `path/to/qt/qmake sandbox.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 && /usr/bin/make qmake_all`
2. run `make`
3. Binaries must be placed in `sandbox/bin`

2021-05-04 18:43 UTC, jrainville approved these changes
Great work!

2021-05-04 19:19 UTC, PascalPrecht requested changes

2021-05-04 19:19 UTC, PascalPrecht commented on sandbox/main.qml
> +            text: "inputs"
This should probably be "Inputs" then

2021-05-04 19:19 UTC, PascalPrecht commented on sandbox/main.qml
> +        }
I don't believe it make sense to have this one as there most likely won't be multiple text style components (probably just `StatusText` which can then be adjusted in size and weight).

2021-05-04 19:19 UTC, PascalPrecht commented on sandbox/main.qml
> +                color: "#2c2c2c"
Now that #23 has landed, we can make use of `Theme.palette.baseColor5` here.

2021-05-04 19:29 UTC, PascalPrecht commented
Really great work indeed!

I've noticed that, after running this, there's untracked `.qmake.stash` and `MakeFile` files.
Can you add them to `.gitignore` please?

2021-05-05 05:57 UTC, PascalPrecht approved these changes

2021-05-05 05:57 UTC, PascalPrecht commented
This has landed as https://github.com/status-im/StatusQ/commit/3528b2ff440a8fb66609f7087f062643f5082132
(I've updated your commit message so it automatically closes #5)

Awesome work Boris!

2021-05-05 05:57 UTC, closed without merging