[#202] Added ColorPicker button
status-im/StatusQ pull request #247
Opened 2021-07-08 12:04 UTC by alexandraB99

Adding color picker button
* Qt's ColorDialog is used for now which opens
  in a different window, however an integrated
  solution should be found

Also minor improvements in main.qml and sandbox.pro

fixes #202

2021-07-08 15:00 UTC, PascalPrecht requested changes
Nice PR @alexandraB99 !

I've tested this locally and it seems to work great! There's a few things I've noticed that need adjustment though. I've left some comments inline. Let me know what you think.

I've also noticed that the color selector renders all black when it opens. Not sure if that is something that's in our control.
<img width="236" alt="Screenshot 2021-07-08 at 16 57 18" src="https://user-images.githubusercontent.com/445106/124944391-8f66ae80-e00d-11eb-9e46-e86f5a0b6c89.png">

Bonus points if you update your commit message to look more like something like:

```
feat(Controls): introduce StatusColorSelectorButton

# your message body

Closes #202
```

Where `StatusColorSelectorButton` is just another name I've proposed as `PickerButton` doesn't really tell us anything.

Lemme know if I can help with anything!

2021-07-08 15:21 UTC, PascalPrecht commented on sandbox/Buttons.qml
> +        }
As discussed offline, I totally confused how this thing is behaving. There's no color selector shipping with that button.

Ignore all the comments made above! 🙏

2021-07-08 15:23 UTC, PascalPrecht commented on src/StatusQ/Controls/qmldir
> +StatusPickerButton 0.1 StatusPickerButton.qml
As mentioned here https://github.com/status-im/StatusQ/pull/247#discussion_r666294544 I totally confused the semantics of this component. No rename needed!

2021-07-08 15:26 UTC, PascalPrecht commented
Once https://github.com/status-im/StatusQ/pull/247#discussion_r666268636 and https://github.com/status-im/StatusQ/pull/247#discussion_r666271034 are addressed we can merge this!

2021-07-09 07:50 UTC, alexandraB99 commented on src/StatusQ/Controls/StatusPickerButton.qml
> +        }
Left and right margins added :) Also Label replaced with a StatusBaseText. As about the color, I see in Figma the text has #939BA1 which points to baseColor1, what am I missing?

2021-07-09 09:01 UTC, PascalPrecht commented on src/StatusQ/Controls/StatusPickerButton.qml
> +        }
Looks like we're looking at different designs! :D

2021-07-09 09:09 UTC, PascalPrecht commented on src/StatusQ/Controls/StatusPickerButton.qml
> +        }
So to clarify, the color change needed was in the icon (see: https://github.com/status-im/StatusQ/pull/247#discussion_r666271034) not the text

2021-07-09 09:15 UTC, PascalPrecht approved these changes

2021-07-09 09:16 UTC, merged

2021-07-09 09:16 UTC, PascalPrecht commented
Landed 🎉 awesome work!