feat(Drag&Drop): Add drag and drop functionality on StatusChatListItem
status-im/StatusQ pull request #300
Opened 2021-07-28 11:09 UTC by borismelnik

2021-07-28 11:19 UTC, PascalPrecht commented
I haven't reviewed the code yet, but I checked out the PR to see how it works. Unfortunately this isn't working well.
Here's what I ran into:

1.  Dragged items don't snap properly into position. I doubt we want items to be positioned anywhere. Below is a screenshot of how I was able to arrange some of the list items:
<img width="429" alt="Screenshot 2021-07-28 at 13 16 59" src="https://user-images.githubusercontent.com/445106/127313737-cbec2c03-5f73-46f2-8201-455769b84f38.png">

2. It's even worse with categories:
<img width="321" alt="Screenshot 2021-07-28 at 13 18 39" src="https://user-images.githubusercontent.com/445106/127313960-f3b000fc-48a3-4b47-b143-00818cf966bd.png">

3. It doesn't seem like dragging into other categories is possible (is that intended?)

2021-08-04 20:45 UTC, iurimatias requested changes
doesn't work for me see video


https://user-images.githubusercontent.com/176720/128252394-680143c9-c309-4d77-9a97-e3c5f27cb705.mov

2021-08-05 08:07 UTC, PascalPrecht requested changes

2021-08-05 08:07 UTC, PascalPrecht commented on src/StatusQ/Components/StatusChatListItem.qml
> +            }
This is problematic. By rebuilding the item component this way, we're losing a lot of its properties. The result is that e.g. the font weight changes when it's dragged, or that we lose various badges and icons.

Can we make sure that, when a chat list item is dragged, it doesn't lose its properties?

2021-08-05 08:10 UTC, PascalPrecht commented
One more thing:

As @iurimatias pointed out, this is not working well in the categories view. Can we introduce a flag to disable drag support by default? That way we don't break existing UIs when this lands and StatusQ dependency is updated.

Status Desktop would then have to explicitely turn on drag support in the chat view (therefore not affecting the communities view with categories).

It works great for single chat lists though, so I think once the comments are ironed out, we can land this!

Oh, and please update your commit message to something like

```
feat(StatusChatList): introduce drag & drop support
```

2021-08-20 10:16 UTC, PascalPrecht commented
Closing this in favour of https://github.com/status-im/StatusQ/pull/339

@borismelnik I kept you as a committer, but I've moved some things around. Namely, the `DropArea` and `Drag` capabilities I've moved into `StatusChatList`. Two reasons why I've done this:

1. Semantically, chat items are drag'n'droppable inside of a list, not as standalone items
2. We actually need to reuse entire `StatusChatListItem` components for the drag effect, so drag and drop capabilities need to be decoupled from that component.

2021-08-20 10:16 UTC, closed without merging