feat(StatusChatList): Highlight chat item at creation time
status-im/StatusQ pull request #560
Opened 2022-02-17 14:12 UTC by borismelnik

Part of: https://github.com/status-im/status-desktop/issues/4767

2022-02-18 08:29 UTC, PascalPrecht requested changes
I'm not sure I fully understand why this is needed. I'd assume the data provided will highlight the correct chat list item no?

If this change is still needed, can you please update the commit message to be a feature commit for StatusChatList?

2022-02-18 08:38 UTC, borismelnik commented
> I'm not sure I fully understand why this is needed. I'd assume the data provided will highlight the correct chat list item no?
> 
> If this change is still needed, can you please update the commit message to be a feature commit for StatusChatList?

@PascalPrecht yeah that property used for `highlight chat item at creation time ` and  should be `invalidated` after first click.

2022-02-18 08:41 UTC, borismelnik commented
it happens when app received message with `chatDto` with property `highlight: true`, which means app should tell user about some changes. Unfortunately, the `chatDto` has zero unread messages or notifications.

2022-02-21 07:46 UTC, PascalPrecht approved these changes

2022-02-21 07:46 UTC, merged