wip fix(Controls): Regex validatior and add ignoreInvalidInput to StatusInput
status-im/StatusQ pull request #576
Opened 2022-03-10 15:54 UTC by stefandunca

Fixes `StatusRegularExpressionValidator` not working if present in `StatusInput.validators`
field. It worked only in `StatusPinInput.validator`, which makes assumptions about internals.

Other improvements:
- [ ] test the validator
- [x] add optional feature to StatusInput not to allow typing characters that are not validated
- [x] add a test entry in the sandbox app.

## Screenshots

New entry
![image](https://user-images.githubusercontent.com/47554641/157698697-b023f7b9-731b-4f68-b3d9-dfc0dba8ec8c.png)

Allow typing only what matches regex
![image](https://user-images.githubusercontent.com/47554641/157699706-c6b8f367-192d-4317-8f05-d92661b219bc.png)

updates #4961

2022-03-10 16:07 UTC, PascalPrecht requested changes
This was marked as WIP, but I still went ahead to take a look.

Few things:

There's two things happening here 1) a fix in the regex validator and 2) a new feature in `StatusInput`.

Can you make this two atomic commits for both of these things, taking into account that each of them have their scope (`fix` and `feat` for `StatusRegexValidator` and `StatusInput` respectively)?

Otherwise, great stuff!
Also @noeliaSD might want to see some documentation for the newly introduced feature.

2022-03-10 16:07 UTC, PascalPrecht commented on src/StatusQ/Controls/StatusInput.qml
> +    property bool ignoreInvalidInput: false
This is a cool feature. Could consider introducing a new `ValidationMode` for that instead of introducing a new prop, but I'm happy to keep this.

2022-03-10 16:10 UTC, PascalPrecht commented
@stefandunca this can be rebased on top of https://github.com/status-im/StatusQ/pull/573 which has just landed in master, which means you only need the feature commit

2022-03-10 16:29 UTC, stefandunca commented
Thanks for the heads up, will make the required changes

2022-03-14 08:41 UTC, PascalPrecht approved these changes
Nice job! Love that it includes tests and docs :)
This just needs a rebase

2022-03-14 09:43 UTC, merged

2022-03-16 06:27 UTC, noeliaSD commented
Late answer but just only want to say.. Super nice that it includes unit tests!! Thanks @stefandunca for introducing them in the project!! :)