feat(StatusToastMessage): Adding component documentation
status-im/StatusQ pull request #621
Opened 2022-04-05 17:25 UTC by alexandraB99

Part of #616

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [x] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [ ] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-04-06 08:28 UTC, noeliaSD requested changes

2022-04-06 08:28 UTC, noeliaSD commented on src/StatusQ/Components/StatusToastMessage.qml
> +        This function is used to open the ToastMessage setting all its properties.
You can use `\qmlmethod` for functions!

2022-04-06 21:19 UTC, alexandraB99 commented on src/StatusQ/Components/StatusToastMessage.qml
> +        This function is used to open the ToastMessage setting all its properties.
done!

2022-04-07 06:42 UTC, noeliaSD approved these changes

2022-04-07 20:48 UTC, iurimatias approved these changes

2022-04-07 20:49 UTC, merged