fix(StatusSlider): Fixed background behavior
status-im/StatusQ pull request #667
Opened 2022-05-11 16:13 UTC by igor-sirotin

Fixes #644

https://user-images.githubusercontent.com/25482501/168081101-da5867e7-4186-4390-a2a7-750bd338e414.mov

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [ ] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-05-12 06:47 UTC, stefandunca requested changes
I see you have a merge commit. Note that we are using a rebasing workflow to keep the history clean. Please see: https://hackmd.io/MVIfVN0yQdOyhYJP0LLLKQ#Submitting-a-Pull-Request-PR

Usually, we add a screenshot/animation for important states to help reviewers understand better the outcome.

In case the PR is unfinished we prefix the title with `WIP` so the intention is clear

2022-05-12 06:47 UTC, stefandunca commented on src/StatusQ/Controls/StatusSlider.qml
> +//        Rectangle {
Do you plan to reuse it in a future update of this PR? For sure, we don't want to keep commented dead code around.

2022-05-12 08:45 UTC, PascalPrecht commented
@igor-sirotin if you need help with rebasing, let me know.

2022-05-12 15:33 UTC, osmaczko approved these changes

2022-05-13 07:01 UTC, stefandunca approved these changes

2022-05-13 10:57 UTC, alexandraB99 approved these changes

2022-05-13 18:24 UTC, merged