fix(StatusImageCrop): fix wrong initial image fit
status-im/StatusQ pull request #685
Opened 2022-05-20 20:15 UTC by stefandunca

The initial fit was computed for the square crop-window

updates: 5118

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [x] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-05-23 18:56 UTC, osmaczko approved these changes

2022-05-24 07:35 UTC, MishkaRogachev requested changes

2022-05-24 07:35 UTC, MishkaRogachev commented on src/StatusQ/Components/StatusImageCropPanel.qml
> +            cropEditor.setCropRect(cropEditor.fillContentInWindow(root.sourceSize, Qt.size(1000, 1000/root.aspectRatio)))
Probably it is better to store size as property and be able to overwrite default 1000 value

2022-05-24 17:49 UTC, MishkaRogachev approved these changes

2022-05-26 00:00 UTC, merged