feat(StatusCard): Create a new reusbale card component
status-im/StatusQ pull request #731
Opened 2022-06-14 16:54 UTC by Khushboo-dev-cpp

closes #582

### Checklist

- [ ] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [ ] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-06-29 11:02 UTC, caybro commented on src/StatusQ/Components/StatusCard.qml
> +       \qmlproperty bool StatusCard::disabledText
`\qmlproperty string ...`

2022-06-29 11:02 UTC, caybro commented on src/StatusQ/Components/StatusCard.qml
> +       \qmlproperty Text StatusCard::primaryLabel
`\qmlproperty alias ~`

Same below

2022-07-12 13:44 UTC, caybro requested changes
Just 2 minor things, otherwise looks good. Sorry for not noticing earlier :)

2022-07-12 13:44 UTC, caybro commented on src/StatusQ/Components/StatusCard.qml
> +    id: statusCard
"root" please :)

2022-07-12 13:44 UTC, caybro commented on src/StatusQ/Core/Utils/Utils.qml
> +        context.strokeStyle = color ? color : '#627EEA'
Shouldn't that color come from a Theme? Will it always be the same for light/dark?

2022-07-12 15:23 UTC, alexandraB99 approved these changes
excelent, lgtm! just the comments from @caybro :)

2022-07-13 19:58 UTC, caybro approved these changes

2022-07-13 22:03 UTC, merged