fix(StatusMessage): Design update and minor improvements
status-im/StatusQ pull request #752
Opened 2022-07-04 15:20 UTC by igor-sirotin

Requires: https://github.com/status-im/StatusQ/pull/815

This one is for https://github.com/status-im/status-desktop/issues/6334.

- `StatusMessageDetailes` refactoring
-  Usernames designs as in https://github.com/status-im/status-desktop/issues/6124
- Added colored line to the left of `isPinned` and `hasMention` messages (as per designs)
- Fixed `StatusMessage` size calculation

NOTE: This PR contains changes in `StatusSelect`. This changes are temporary and will be removed by me before merging.
This is because without that workaround the app just doesn't start :)
I will fix that using #790 and test it with this PR.

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [x] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-07-04 16:41 UTC, caybro requested changes

2022-07-04 16:41 UTC, caybro commented on src/StatusQ/Components/StatusMessage.qml
> +                                        return Qt.formatTime(new Date(parsed), "hh:mm");
This should respect the user's locale, see https://doc.qt.io/qt-5/qml-qtqml-date.html#toLocaleTimeString-method

2022-07-04 16:41 UTC, caybro commented on src/StatusQ/Components/StatusMessageSenderDetails.qml
> +    property var trustIndicator: StatusContactVerificationIcons.TrustedType.None
`int`?

2022-07-04 16:41 UTC, caybro commented on src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
> +    property var trustIndicator: sender.trustIndicator
`int`

2022-07-04 16:41 UTC, caybro commented on src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
> +            text: `(${root.sender.secondaryName})`
hmm, why the format string here? :)

2022-07-04 16:52 UTC, caybro commented on src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
> +            text: `(${root.sender.secondaryName})`
Ah lol my bad, I was kinda assuming `"` there as well :D

2022-07-27 16:15 UTC, jrainville approved these changes
Looks good, good job.

There are a lot of TODOs, maybe it would be worth to log them in some tickets after the merge to keep track of them

2022-07-28 18:57 UTC, osmaczko approved these changes

2022-07-28 18:57 UTC, osmaczko commented on src/StatusQ/Components/StatusMessage.qml
> +    ]
```suggestion
    property var reactionIcons: [ ❤, 👍, 👎, 🤣, 😥, 😠]
```
I believe you could use unicode emojis here for better readability, then use `StatusQ.Emoji` to parse it.

2022-07-29 06:21 UTC, osmaczko commented on src/StatusQ/Components/StatusMessage.qml
> +    ]
Ok, that makes sense, didn't know status-destkop uses emoji images different than those provided in twemoji.

2022-07-29 06:24 UTC, osmaczko commented on src/StatusQ/Components/StatusMessage.qml
> +    ]
To be fair it still may be simplified:
```
    property var reactionIcons: [
        Emoji.iconSource("❤"),
        Emoji.iconSource("👍"),
        ...
        Emoji.iconSource("😠")
    ]
```
but that's not critical :D

2022-08-01 19:07 UTC, caybro requested changes
Some comments inline

2022-08-01 19:07 UTC, caybro commented on src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml
> +            tooltip += qsTr(" reacted with ");
No :( Please don't glue the text like this, use `qsTr("%1 reacted with %2).arg(foo).arg(bar)`

2022-08-01 19:07 UTC, caybro commented on src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml
> +                property bool isHovered: false // TODO: readonly, use mouseArea.containsMouse
Time to fix since this is a new file? ;)

2022-08-01 19:07 UTC, caybro commented on src/StatusQ/Components/private/statusMessage/StatusMessageEmojiReactions.qml
> +                property bool isHovered: false // TODO: Replace with mouseArea.containsMouse
FIXIT :)

2022-08-01 19:07 UTC, caybro commented on src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml
> +            // Strange thing. Without this empty stub the cursorShape
Hmm? :)

2022-08-01 19:07 UTC, caybro commented on src/StatusQ/Core/StatusProfileImageSettings.qml
> +    property var colorHash // TODO: default value Utils.getColorHashAsJson(pubkey)
Still TODO?

2022-08-12 12:57 UTC, caybro approved these changes
LGTM

2022-08-19 15:06 UTC, micieslak approved these changes
Looks like a lot of good job! Lgtm, but I left some comments.

2022-08-19 15:06 UTC, micieslak commented on src/StatusQ/Core/Utils/Utils.qml
> +        return `<style type="text/css">` +
I'm not 100% sure, but probably it could be done by using single pair of ``. Then all + could be removed making it cleaner.

2022-08-19 15:06 UTC, micieslak commented on src/StatusQ/Core/Utils/Utils.qml
> +        var replacePattern1 = /(\b(https?|ftp|statusim):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gim;
const

2022-08-20 00:01 UTC, merged