fix(demoapp): Replaced non-existent web images with locals
status-im/StatusQ pull request #757
Opened 2022-07-06 11:44 UTC by igor-sirotin

The [original image]("https://pbs.twimg.com/profile_images/1369221718338895873/T_5fny6o_400x400.jpg") doesn't exist anymore. Replaced it with another local image.

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [ ] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-07-06 11:52 UTC, caybro approved these changes

2022-07-06 12:05 UTC, osmaczko approved these changes

2022-07-06 12:21 UTC, MishkaRogachev requested changes

2022-07-06 12:38 UTC, caybro commented on sandbox/controls/Controls.qml
> +        icon.source: "qrc:/demoapp/data/profile-image-1.jpeg"
Not true, `ListElement` does support dynamic values too

2022-07-06 12:39 UTC, caybro commented on sandbox/controls/Controls.qml
> +        icon.source: "qrc:/demoapp/data/profile-image-1.jpeg"
> Beginning with Qt 5.11 ListElement also allows assigning a function declaration to a role. This allows the definition of ListElements with callable actions.

See https://doc.qt.io/qt-5/qml-qtqml-models-listelement.html

2022-07-07 07:20 UTC, PascalPrecht requested changes
@igor-sirotin So to give some context here: There are some image sources in the model here that **meant to** return a 404, so that the components that make use of it, fallback to something else.

For example, in the case of list item profile pictures, if the picture can't be loaded for whatever reason, the letter identicon will be shown.

With that said, I'm not sure this PR can be merged because by maybe all of those image sources local, we no longer test the error case.

2022-07-07 16:55 UTC, caybro commented on sandbox/controls/Controls.qml
> +        icon.source: "qrc:/demoapp/data/profile-image-1.jpeg"
Right, it's still an improvement, as now you can do things like:
```qml
ListElement { text: qsTr("Translate me!") }
```
which were not possible before :)

2022-07-08 11:03 UTC, PascalPrecht reviewed
@igor-sirotin Seems like there's only one spot where we do the fallback.
Feel free to change the endpoint to something else if you think it's necessary.
Otherwise, this PR can prolly be merged.

2022-07-08 11:03 UTC, PascalPrecht commented on sandbox/controls/Controls.qml
> +        icon.source: "qrc:/demoapp/data/profile-image-1.jpeg"
@igor-sirotin This one has a comment that states the fallback

2022-07-08 11:03 UTC, PascalPrecht commented on sandbox/controls/Controls.qml
> +        icon.source: "qrc:/demoapp/data/profile-image-1.jpeg"
Actually, seems like only this one has a broken URL on purpose

2022-07-13 19:04 UTC, MishkaRogachev approved these changes
LGTM!

2022-07-14 08:21 UTC, PascalPrecht approved these changes

2022-07-22 13:42 UTC, merged