fix(StatusScrollView): use Flickable underhood to ScrollView issues
status-im/StatusQ pull request #784
Opened 2022-07-15 15:18 UTC by MishkaRogachev

For https://github.com/status-im/status-desktop/pull/6456

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [x] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-07-15 15:25 UTC, caybro requested changes

2022-07-15 15:25 UTC, caybro commented on src/StatusQ/Core/StatusScrollView.qml
> +    property Item background: Item {}
`: null` is empty

2022-07-18 07:11 UTC, noeliaSD approved these changes

2022-07-18 10:46 UTC, caybro approved these changes
Looks good!

2022-07-19 07:18 UTC, noeliaSD approved these changes

2022-07-19 08:57 UTC, MishkaRogachev commented
@caybro @noeliaSD i'm thinking about renaming StatusScrollView to StatusFlickable for few reasons:
- Since Qt 5.15 Flickable have [own](https://doc-snapshots.qt.io/qt5-5.15/qml-qtquick-flickable.html#leftMargin-prop) margins
- In status desktop we often use ScrollView for decoration ListView with scrollbars. But within my changes it has no sense, because StatusListView already have scrollbars.

2022-07-19 09:16 UTC, caybro commented
> @caybro @noeliaSD i'm thinking about renaming StatusScrollView to StatusFlickable for few reasons:
> 
> * Since Qt 5.15 Flickable have [own](https://doc-snapshots.qt.io/qt5-5.15/qml-qtquick-flickable.html#leftMargin-prop) margins
> * In status desktop we often use ScrollView for decoration ListView with scrollbars. But within my changes it has no sense, because StatusListView already have scrollbars.

I wouldn't mind either way... but notice the `margins` have been there for some time already afaik (not new in 5.15) and also the correct way to decorate a `ListView` with scrollbars would be with the `ScrollBar.vertical: ScrollBar{}` attached property

2022-07-21 13:24 UTC, merged