feature(Components): Implement generic address display control
status-im/StatusQ pull request #826
Opened 2022-08-03 12:50 UTC by stefandunca

### Checklist

- [ ] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [ ] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-08-04 11:15 UTC, MishkaRogachev approved these changes
Layouts are cool

2022-08-04 11:42 UTC, caybro requested changes
Looks good, some minor stuff only

2022-08-04 11:42 UTC, caybro commented on src/StatusQ/Components/StatusAddressPanel.qml
> +        cursorShape: root.expandable ? Qt.PointingHandCursor : Qt.arrowCursor
`Qt.ArrowCursor` typo

2022-08-04 11:42 UTC, caybro commented on src/StatusQ/Components/StatusAddress.qml
> +    property int preferredWidth: expanded ? actualWidth : maxWidth
`readonly`?

2022-08-05 14:54 UTC, caybro approved these changes
Good stuff!

2022-08-05 15:01 UTC, merged