fix(StatusMessageEmojiReactions): Fixed emoji reactions appearance
status-im/StatusQ pull request #889
Opened 2022-09-08 07:59 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/5986

### What does this PR do?

- Replaced emoji reactions border with background fill
- If message was sent by current user (You), the "small-radius" corner was at top-right - moved to top-left (per design)
- Refactored emoji reaction content using `Row` and paddings

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/25482501/189067291-aa09cd19-8f7e-4f54-9418-33469835c965.png">

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/25482501/189068079-58d439fb-32e9-4805-94d4-06b2a1355f95.png">

### Checklist

- [x] follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - the scope should be the component's name e.g: `feat(StatusListItem): ... `
  - when adding new components, the scope is the module e.g: `feat(StatusQ.Controls): ...`
- [ ] add documentation if necessary (new component, new feature)
- [x] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?
- [ ] is this a breaking change?
    - [ ] use the dedicated `BREAKING CHANGE` commit message section
    - [ ] resolve breaking changes in [status-desktop](https://github.com/status-im/status-desktop)
        - [ ] (pre-merge) adapt code to breaking changes
        - [ ] (post-merge) update StatusQ submodule pointer
- [x] test changes in [status-desktop](https://github.com/status-im/status-desktop)

2022-09-08 08:11 UTC, caybro requested changes

2022-09-08 08:11 UTC, caybro commented on src/StatusQ/Core/Theme/StatusLightTheme.qml
> +        property color emojiReactionActiveBackgroundHovered: Qt.darker(emojiReactionActiveBackground, 1.1)
What about the dark theme?

2022-09-08 12:32 UTC, caybro approved these changes
Looks good!

2022-09-09 17:42 UTC, alexandraB99 approved these changes
aaah perfect! thanks for this! :)

2022-09-10 03:22 UTC, merged